language: csharp
notifications:
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
mono: none
dotnet: 2.2.101
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: false
    - os: osx
      osx_image: xcode9.1
install:
  - npm install
  - dotnet restore
script:
  - node ./ldap.js &
  - cd ./test/Unosquare.Swan.Ldap.Test/
  - dotnet test Unosquare.Swan.Ldap.Test.csproj -s .runsettings -f netcoreapp2.2
after_script:
  - killall -9 node
